format_version: 10
pipelines:
  phileas:
    environment_variables:
      JAVA_HOME: /usr/lib/jvm/java-1.11.0-openjdk-amd64
      PHILTER_REDIS_HOST: 127.0.0.1
      PHILTER_REDIS_PORT: 6379
      PHILTER_REDIS_SSL: false
      PHILTER_REDIS_AUTH_TOKEN:
      PHILTER_REDIS_CLUSTERED: false
    group: build
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-9b017ff:
        git: git@bitbucket.org:mountainfog/phileas.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build-And-Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - build.sh
                run_if: passed
