format_version: 10
environments:
  dev:
    environment_variables:
      JAVA_HOME: /usr/lib/jvm/java-1.11.0-openjdk-amd64
    pipelines:
      - phileas
pipelines:
  phileas:
    group: github-projects
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-9b017ff:
        git: git@bitbucket.org:mountainfog/phileas.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build-And-Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - install
                command: mvn
                run_if: passed
